### ISSUE TITLE
"Uncaught (in promise): No provider for Configuration! (Home -> DataService -> Configuration)"

### ISSUE THREAD

**Issue by felipedrumond** [FabianGosebrink/ASPNET-Core-Angular2-StarterTemplate#2] opened 2016-05-21 15:03 UTC
Hi. I'm getting "no provider error for Configuration" when using DataService in Home component, but if I add Configurations to the providers list, it works. Do I really need to add Configuration to the component?

This does not work
```
@Component({
    selector: 'home',
    templateUrl: 'app/home/home.component.html',
    directives: [CORE_DIRECTIVES],
    providers:[DataService]
})
```
This works
```
@Component({
    selector: 'home',
    templateUrl: 'app/home/home.component.html',
    directives: [CORE_DIRECTIVES],
    providers:[DataService, Configuration]
})
```

**Comment by FabianGosebrink** [comment] 2016-05-25 12:00
Hey felipe, I could not reproduce the issue. I just updated to RC2. Want to try again?

Best regards

Fabian

**Comment by FabianGosebrink** [comment] 2016-07-01 05:13
closing this now...

**Closed by FabianGosebrink** 2016-07-01 05:13 UTC
